/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.19.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  admins: string[];
}
export type ExecuteMsg = {
  update_admins: {
    admins: string[];
  };
} | {
  update_config: {
    config: Config;
  };
} | {
  update_marketing: {
    marketing: Marketing;
  };
} | {
  withdraw: {
    amount?: Uint128 | null;
  };
} | {
  create_listing: {
    active: boolean;
    attributes: Attributes;
    options: ListingOption[];
    price: Uint128;
  };
} | {
  update_listing: {
    active: boolean;
    attributes: Attributes;
    id: number;
    options: ListingOption[];
    price: Uint128;
  };
} | {
  delete_listing: {
    id: number;
  };
} | {
  update_order: {
    id: number;
    status: OrderStatus;
    tracking?: TrackingInfo | null;
  };
} | {
  complete_order: {
    id: number;
  };
} | {
  refund_order: {
    id: number;
  };
} | {
  create_order: {
    items: OrderItem[];
  };
} | {
  cancel_order: {
    id: number;
  };
} | {
  receive: Cw20ReceiveMsg;
};
export type Uint128 = string;
export type Network = "Twitter" | "Facebook" | "GitHub" | "LinkedIn" | "Instagram" | "YouTube" | "Reddit" | "Medium" | "Discord" | "TikTok" | "Twitch";
export type OrderStatus = "Received" | "Fulfilling" | "Shipped";
export type Binary = string;
export interface Config {
  denom: string;
  withdrawal_address: string;
  [k: string]: unknown;
}
export interface Marketing {
  copyright?: string | null;
  featured_listings: Listing[];
  logo?: string | null;
  name: string;
  socials: Social[];
  [k: string]: unknown;
}
export interface Listing {
  active: boolean;
  attributes: Attributes;
  id: number;
  options: ListingOption[];
  price: Cw20Coin;
  [k: string]: unknown;
}
export interface Attributes {
  description?: string | null;
  images: string[];
  name: string;
  [k: string]: unknown;
}
export interface ListingOption {
  description?: string | null;
  id: number;
  name: string;
  options: ListingOptionItem[];
  [k: string]: unknown;
}
export interface ListingOptionItem {
  cost?: Cw20Coin | null;
  name: string;
  [k: string]: unknown;
}
export interface Cw20Coin {
  address: string;
  amount: Uint128;
}
export interface Social {
  network: Network;
  url: string;
  [k: string]: unknown;
}
export interface TrackingInfo {
  provider: string;
  url: string;
  [k: string]: unknown;
}
export interface OrderItem {
  amount: number;
  listing_id: number;
  options: OrderOption[];
  [k: string]: unknown;
}
export interface OrderOption {
  option_id: number;
  selected_option: ListingOptionItem;
  [k: string]: unknown;
}
export interface Cw20ReceiveMsg {
  amount: Uint128;
  msg: Binary;
  sender: string;
}
export type QueryMsg = {
  config: {};
} | {
  admin_list: {};
} | {
  can_execute: {
    sender: string;
  };
} | {
  withdrawable_balance: {};
} | {
  locked_balance: {};
} | {
  marketing: {};
} | {
  orders: {};
} | {
  order: {
    id: number;
  };
} | {
  listings: {};
} | {
  listing: {
    id: number;
  };
};
export interface AdminListResponse {
  admins: string[];
}
export interface CanExecuteResponse {
  can_execute: boolean;
}
export interface ConfigResponse {
  config: Config;
}
export interface ListingResponse {
  listing?: Listing | null;
}
export interface ListingsResponse {
  listings: Listing[];
}
export interface BalanceResponse {
  balance: Cw20Coin;
}
export interface MarketingResponse {
  marketing: Marketing;
}
export type Addr = string;
export interface OrderResponse {
  order?: Order | null;
}
export interface Order {
  buyer: Addr;
  id: number;
  items: OrderItem[];
  status: OrderStatus;
  tracking?: TrackingInfo | null;
  [k: string]: unknown;
}
export interface OrdersResponse {
  orders: Order[];
}