/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.19.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./Commerce.types";
import * as _1 from "./Commerce.client";
import * as _2 from "./Commerce.message-composer";
import * as _3 from "./Commerce.recoil";
import * as _4 from "./Trust.types";
import * as _5 from "./Trust.client";
import * as _6 from "./Trust.message-composer";
import * as _7 from "./Trust.recoil";
export namespace contracts {
  export const Commerce = { ..._0,
    ..._1,
    ..._2,
    ..._3
  };
  export const Trust = { ..._4,
    ..._5,
    ..._6,
    ..._7
  };
}