/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.19.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { Coin, StdFee } from "@cosmjs/amino";
import { Uint128, InstantiateMsg, TrustScoreParams, ExecuteMsg, ReviewResult, QueryMsg, Addr, AccountsResponse, StakeAmountResponse, TrustInfoResponse, TrustInfo, TrustData } from "./Trust.types";
export interface TrustReadOnlyInterface {
  contractAddress: string;
  trustInfo: ({
    address
  }: {
    address: string;
  }) => Promise<TrustInfoResponse>;
  stakeAmount: ({
    address
  }: {
    address: string;
  }) => Promise<StakeAmountResponse>;
  accounts: () => Promise<AccountsResponse>;
}
export class TrustQueryClient implements TrustReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;

  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.trustInfo = this.trustInfo.bind(this);
    this.stakeAmount = this.stakeAmount.bind(this);
    this.accounts = this.accounts.bind(this);
  }

  trustInfo = async ({
    address
  }: {
    address: string;
  }): Promise<TrustInfoResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      trust_info: {
        address
      }
    });
  };
  stakeAmount = async ({
    address
  }: {
    address: string;
  }): Promise<StakeAmountResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      stake_amount: {
        address
      }
    });
  };
  accounts = async (): Promise<AccountsResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      accounts: {}
    });
  };
}
export interface TrustInterface extends TrustReadOnlyInterface {
  contractAddress: string;
  sender: string;
  updateConfig: ({
    admin,
    maintainer,
    maxRating,
    maxStakedDays,
    maxStakedTokens,
    reviewInterval,
    stakingContract,
    trustScoreParams
  }: {
    admin: string;
    maintainer: string;
    maxRating: number;
    maxStakedDays: number;
    maxStakedTokens: Uint128;
    reviewInterval: number;
    stakingContract: string;
    trustScoreParams: TrustScoreParams;
  }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
  updateStakingInfo: ({
    address
  }: {
    address: string;
  }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
  review: ({
    address,
    result
  }: {
    address: string;
    result: ReviewResult;
  }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
}
export class TrustClient extends TrustQueryClient implements TrustInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;

  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.updateConfig = this.updateConfig.bind(this);
    this.updateStakingInfo = this.updateStakingInfo.bind(this);
    this.review = this.review.bind(this);
  }

  updateConfig = async ({
    admin,
    maintainer,
    maxRating,
    maxStakedDays,
    maxStakedTokens,
    reviewInterval,
    stakingContract,
    trustScoreParams
  }: {
    admin: string;
    maintainer: string;
    maxRating: number;
    maxStakedDays: number;
    maxStakedTokens: Uint128;
    reviewInterval: number;
    stakingContract: string;
    trustScoreParams: TrustScoreParams;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_config: {
        admin,
        maintainer,
        max_rating: maxRating,
        max_staked_days: maxStakedDays,
        max_staked_tokens: maxStakedTokens,
        review_interval: reviewInterval,
        staking_contract: stakingContract,
        trust_score_params: trustScoreParams
      }
    }, fee, memo, funds);
  };
  updateStakingInfo = async ({
    address
  }: {
    address: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_staking_info: {
        address
      }
    }, fee, memo, funds);
  };
  review = async ({
    address,
    result
  }: {
    address: string;
    result: ReviewResult;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      review: {
        address,
        result
      }
    }, fee, memo, funds);
  };
}