/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.19.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Uint128 = string;
export interface InstantiateMsg {
  maintainer: string;
  max_rating: number;
  max_staked_days: number;
  max_staked_tokens: Uint128;
  review_interval: number;
  staking_contract: string;
  trust_score_params: TrustScoreParams;
}
export interface TrustScoreParams {
  base_score: number;
  min_stake_days: number;
  rating_floor_denominator: number;
  rating_multiplier: number;
  stake_amount_denominator: number;
  [k: string]: unknown;
}
export type ExecuteMsg = {
  update_config: {
    admin: string;
    maintainer: string;
    max_rating: number;
    max_staked_days: number;
    max_staked_tokens: Uint128;
    review_interval: number;
    staking_contract: string;
    trust_score_params: TrustScoreParams;
  };
} | {
  update_staking_info: {
    address: string;
  };
} | {
  review: {
    address: string;
    result: ReviewResult;
  };
};
export type ReviewResult = "ThumbsUp" | "ThumbsDown";
export type QueryMsg = {
  trust_info: {
    address: string;
  };
} | {
  stake_amount: {
    address: string;
  };
} | {
  accounts: {};
};
export type Addr = string;
export interface AccountsResponse {
  accounts: Addr[];
}
export interface StakeAmountResponse {
  stake_amount?: Uint128 | null;
}
export interface TrustInfoResponse {
  trust_info?: TrustInfo | null;
}
export interface TrustInfo {
  data: TrustData;
  score: number;
  [k: string]: unknown;
}
export interface TrustData {
  prev_stake_amount: Uint128;
  rating: number;
  stake_amount: Uint128;
  stake_days: number;
  [k: string]: unknown;
}