/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.19.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Uint128 = string;
export interface InstantiateMsg {
  commerce_code_id: number;
  maintainer: string;
  max_rating: number;
  max_staked_days: number;
  max_staked_tokens: Uint128;
  review_interval: number;
  staking_contract: string;
  trust_score_params: TrustScoreParams;
}
export interface TrustScoreParams {
  base_score: number;
  denom_multiplier: number;
  min_stake_days: number;
  rating_floor_denominator: number;
  rating_multiplier: number;
  stake_amount_denominator: number;
}
export type ExecuteMsg = {
  update_config: {
    admin: string;
    commerce_code_id: number;
    maintainer: string;
    max_rating: number;
    max_staked_days: number;
    max_staked_tokens: Uint128;
    review_interval: number;
    staking_contract: string;
    trust_score_params: TrustScoreParams;
  };
} | {
  update_staking_info: {
    address: string;
  };
} | {
  register_pending_review: {
    order_id: number;
    peer: string;
    reviewer: string;
  };
} | {
  review: {
    address: string;
    review: ReviewResult;
  };
};
export type ReviewResult = "thumbs_up" | "thumbs_down";
export type QueryMsg = {
  config: {};
} | {
  trust_info: {
    address: string;
  };
} | {
  stake_amount: {
    address: string;
  };
} | {
  accounts: {};
} | {
  pending_review: {
    peer: string;
  };
} | {
  pending_reviews_by_reviewer: {
    reviewer: string;
  };
};
export type Addr = string;
export interface AccountsResponse {
  accounts: Addr[];
}
export interface ConfigResponse {
  config: Config;
}
export interface Config {
  admin: Addr;
  commerce_code_id: number;
  maintainer: Addr;
  max_rating: number;
  max_staked_days: number;
  max_staked_tokens: Uint128;
  review_interval: number;
  staking_contract: Addr;
  trust_score_params: TrustScoreParams;
}
export type Timestamp = Uint64;
export type Uint64 = string;
export interface PendingReviewResponse {
  pending_review?: PendingReview | null;
}
export interface PendingReview {
  commerce_contract: Addr;
  expires_at: Timestamp;
  order_id: number;
  peer: Addr;
  reviewer: Addr;
}
export interface PendingReviewsResponse {
  pending_reviews: PendingReview[];
}
export interface StakeAmountResponse {
  stake_amount?: Uint128 | null;
}
export type Decimal = string;
export interface TrustInfoResponse {
  trust_info?: TrustInfo | null;
}
export interface TrustInfo {
  data: TrustData;
  score: Decimal;
}
export interface TrustData {
  prev_stake_amount: Uint128;
  rating: number;
  stake_amount: Uint128;
  stake_days: number;
}